### ISSUE TITLE
マーカーのアイコンを作成する

### ISSUE THREAD

**Issue by taisei-watanabe** [siida36/smart-sauna-map#29]
## 背景

ここまでで主なメイン画面とサウナ検索機能が完成した。
残るタスクは

- 画面デザインにこだわること
  - タイトルロゴの作成
  - サウナマーカーの作成
- テストの作成
  - component 単位のテスト
  - e2e テスト

である。

## 課題

- 現状では白い文字でマーカーが表現されるので、マップの色に重なってしまい視認性が悪い。

## 目的

- サウナマーカーの作成を行い、マップの視認性を向上させる。

## 解決法

- [x] サウナマーカーをデザインする
- [x] サウナマーカーを表現する React コンポーネントを作成する

**Comment by siida36** [comment]
## サウナマーカーの要件（仮）

- [ ] いいね数を反映した画像である
- [ ] クリックしたら小さいウインドウが出現してサウナへのリンクが表示されるようにする

**Comment by siida36** [comment]
## 作業分担

- 飯田: マーカー
- 渡辺: 窓

**Comment by taisei-watanabe** [comment]
- [ ] クリックしたら小さいウインドウが出現してサウナへのリンクが表示されるようにする

はバックエンドの修正が必要なため、一旦後回しする。
